# IMAGEN MODELO
FROM eclipse-temurin:21.0.7_6-jdk

# INORMAR EL PUERTO POR DONDE CORRE O SE EJECUTA EL CONTENEDOR(INFORMATIVO)
EXPOSE 8080

# DEFINIR DIRECTORIO RAIZ DE NUESTRO PROYECTO
WORKDIR /root

# COPIAR Y PEGAR ARCHIVOS DENTRO DE CONTENEDOR
COPY ./pom.xml /root
COPY ./.mvn /root/.mvn
COPY ./mvnw /root

# DESCARGAR LAS DEDPENNDENCIAS
RUN ./mvnw dependency:go-offline

# COPIAR EL CODIGO FUENTE DENTRO EL CONTENEDOR
COPY ./src /root/src

# CONSTRUIR NUESTRA APLICACION
RUN ./mvnw clean install -DskipTest

# LEVENATAR NUESTRA APLICACION CUANDO EL CONTENEDOR INICIE
ENTRYPOINT ["java","-jar","/root/target/SpringDocker-0.0.1-SNAPSHOT.jar"]